---
- name: Install useful packages.
  apt:
    update_cache: yes
    name: "{{ item }}"
    cache_valid_time: 86400
  with_items: "{{ common_packages }}"

# Needed for roles/geerlingguy.php
- name: Install PHP7 repo
  apt_repository:
    repo: ppa:ondrej/php
    state: present
